### ISSUE TITLE
Build fails on current Arch

### ISSUE THREAD

**Issue by jaro3** [puxplaying/gnome-control-center-x11-scaling#10]
[13/552] Compiling C object panels/display/libdisplay.a.p/cc-display-settings.c.o
FAILED: panels/display/libdisplay.a.p/cc-display-settings.c.o 
cc -Ipanels/display/libdisplay.a.p -Ipanels/display -I../gnome-control-center/panels/display -I. -I../gnome-control-center -Ipanels/common -I../gnome-control-center/panels/common -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/gsettings-desktop-schemas -I/usr/include/libadwaita-1 -I/usr/include/gtk-4.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/freetype2 -I/usr/include/graphene-1.0 -I/usr/lib/graphene-1.0/include -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/fribidi -I/usr/include/appstream -I/usr/include/gio-unix-2.0 -I/usr/include/colord-1 -I/usr/include/gnome-desktop-4.0 -I/usr/include/libxml2 -I/usr/include/libupower-glib -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -DHAVE_CONFIG_H -Wno-deprecated-declarations -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -flto=auto -fPIC -pthread -mfpmath=sse -msse -msse2 -mfpmath=sse -msse -msse2 -mfpmath=sse -msse -msse2 '-DG_LOG_DOMAIN="cc-display-panel"' '-DPANEL_ID="display"' '-DDATADIR="/usr/share"' -MD -MQ panels/display/libdisplay.a.p/cc-display-settings.c.o -MF panels/display/libdisplay.a.p/cc-display-settings.c.o.d -o panels/display/libdisplay.a.p/cc-display-settings.c.o -c ../gnome-control-center/panels/display/cc-display-settings.c
../gnome-control-center/panels/display/cc-display-settings.c: In function ‘on_scale_fractional_toggled’:
../gnome-control-center/panels/display/cc-display-settings.c:913:43: error: passing argument 1 of ‘adw_switch_row_get_active’ from incompatible pointer type [-Wincompatible-pointer-types]
  913 |   active = adw_switch_row_get_active (self->scale_fractional_row);
      |                                       ~~~~^~~~~~~~~~~~~~~~~~~~~~
      |                                           |
      |                                           GtkWidget * {aka struct _GtkWidget *}
In file included from /usr/include/libadwaita-1/adwaita.h:77,
                 from ../gnome-control-center/panels/display/cc-display-settings.h:23,
                 from ../gnome-control-center/panels/display/cc-display-settings.c:26:
/usr/include/libadwaita-1/adw-switch-row.h:28:51: note: expected ‘AdwSwitchRow *’ {aka ‘struct _AdwSwitchRow *’} but argument is of type ‘GtkWidget *’ {aka ‘struct _GtkWidget *’}
   28 | gboolean adw_switch_row_get_active (AdwSwitchRow *self);
      |                                     ~~~~~~~~~~~~~~^~~~
[22/552] Compiling C object panels/mouse/libmouse-properties.a.p/cc-mouse-panel.c.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by Lassebq** [comment]
Wrapping value of self->scale_fractional_row with ADW_SWITCH_ROW() fixes it. Please update patches.

**Comment by jaro3** [comment]
> Wrapping value of self->scale_fractional_row with ADW_SWITCH_ROW() fixes it. Please update patches.

can you show a sample replacement line how to wrap it ?

**Comment by puxplaying** [comment]
Thanks for the report! I just pushed 46.1-3, please test if it works for you!

**Comment by Lassebq** [comment]
git repo works, AUR is out of date though
