### ISSUE TITLE
GNOME 42

### ISSUE THREAD

**Issue by puxplaying** [puxplaying/gnome-control-center-x11-scaling#3]
The current Ubuntu release is sticking to version 41 of g-c-c, which unfortunately means that the patches need to be refreshed for the 42 release. 
If you would like to help out, this are the used patches in this package:
[ display-Allow-fractional-scaling-to-be-enabled.patch](https://salsa.debian.org/gnome-team/gnome-control-center/-/blob/ubuntu/master/debian/patches/ubuntu/display-Allow-fractional-scaling-to-be-enabled.patch)
[display-Support-UI-scaled-logical-monitor-mode.patch](https://salsa.debian.org/gnome-team/gnome-control-center/-/blob/ubuntu/master/debian/patches/ubuntu/display-Support-UI-scaled-logical-monitor-mode.patch)

Example PKGBUILD:

```
pkgname=gnome-control-center-x11-scaling
_pkgname=gnome-control-center
pkgver=42.0
pkgrel=1
pkgdesc="GNOME's main interface to configure various aspects of the desktop with X11 fractional scaling patch"
url="https://gitlab.gnome.org/GNOME/gnome-control-center"
license=(GPL2)
arch=(x86_64)
depends=(accountsservice cups-pk-helper gnome-bluetooth-3.0 gnome-desktop-4
         gnome-online-accounts gnome-settings-daemon gsettings-desktop-schemas
         gtk4 libgtop libnma-gtk4 sound-theme-freedesktop upower libpwquality
         gnome-color-manager smbclient libmm-glib libgnomekbd libibus libgudev
         bolt udisks2 libadwaita gsound colord-gtk4 gcr)
makedepends=(docbook-xsl modemmanager git python meson)
checkdepends=(python-dbusmock python-gobject xorg-server-xvfb)
conflicts=($_pkgname)
provides=($_pkgname)
optdepends=('system-config-printer: Printer settings'
            'gnome-user-share: WebDAV file sharing'
            'gnome-remote-desktop: screen sharing'
            'rygel: media sharing'
            'openssh: remote login'
            'power-profiles-daemon: Power profiles support')
groups=(gnome)
options=(debug)
_commit=6199d4058e1d958533569995762b80073abebf17  # tags/42.0^0
source=("git+https://gitlab.gnome.org/GNOME/gnome-control-center.git#commit=$_commit"
        "git+https://gitlab.gnome.org/GNOME/libgnome-volume-control.git"
        "display-Allow-fractional-scaling-to-be-enabled.patch::https://salsa.debian.org/gnome-team/gnome-control-center/-/raw/f9420d5c77f11add188dca9bd018eb14eaecfc3d/debian/patches/ubuntu/display-Allow-fractional-scaling-to-be-enabled.patch"
        "display-Support-UI-scaled-logical-monitor-mode.patch::https://salsa.debian.org/gnome-team/gnome-control-center/-/raw/c72bfaf2b8b1b5d15427bcb7088d11cca356d084/debian/patches/ubuntu/display-Support-UI-scaled-logical-monitor-mode.patch")
sha256sums=('SKIP'
            'SKIP'
            '30aa974e65fdbb699b4d65f892c2a3e25f1bec8d0faf5b5f10c480f735bf538f'
            'f37649cd5b2bac72f511ba52de3e43163dfa6bcbdb419e8f8b14e0cab9c196ef')

pkgver() {
  cd $_pkgname
  git describe --tags | sed 's/[^-]*-g/r&/;s/-/+/g'
}

prepare() {
  cd $_pkgname

  # Install bare logos into pixmaps, not icons
  sed -i "/install_dir/s/'icons'/'pixmaps'/" panels/info-overview/meson.build

  git submodule init subprojects/gvc
  git submodule set-url subprojects/gvc "$srcdir/libgnome-volume-control"
  git submodule update

  # Support UI scaled logical monitor mode (Marco Trevisan, Robert Ancell)
  patch -p1 -i "${srcdir}/display-Allow-fractional-scaling-to-be-enabled.patch"
  patch -p1 -i "${srcdir}/display-Support-UI-scaled-logical-monitor-mode.patch"
}

build() {
  arch-meson $_pkgname build -D documentation=true
  meson compile -C build
}

check() {
  meson test -C build --print-errorlogs
}

package() {
  meson install -C build --destdir "$pkgdir"
  install -d -o root -g 102 -m 750 "$pkgdir/usr/share/polkit-1/rules.d"
}

```

**Comment by tiefling** [comment]
@puxplaying - Is this package still required in Gnome 42?

I've just been digging through this as your packages have made my Manjaro system viable for the last year with my monitor set up (Thanks!)

I have found that after removing this package and installing `gnome-control-center` 42 version instead that I still have fractional scaling options available. I don't have an option to turn it on or off but I have the options to select, as long as I still have `mutter-x11-scaling` installed.

Without knowing more, I'm unsure whether this is a side effect of settings being pre-set effectively as a result of this package being previously installed at the config level or if `gnome-control-center` has been enhanced and that the result can be achieved now purely with `mutter-x11-scaling`.

**Comment by puxplaying** [comment]
Those 2 patches in the `gnome-control-center` package are for two reasons as explained in the [request](https://github.com/puxplaying/mutter-x11-scaling/issues/10) of the developer - Marco Trevisan @3v1n0 .

1. Provide an easy toggle to enable/disable fractional scaling via UI
2. Proper multi-monitor management

Fractional scaling main functionality is however provided by [mutter-x11-scaling](https://github.com/puxplaying/mutter-x11-scaling/blob/master/README.md).

**Comment by tiefling** [comment]
Option 2 here looks to be handled now (I have 1 4k and 1 2k monitor and can configure these properly now in the standard Control Centre, so that may be redundant.

Setting the Fractional Scaling setting would still be a requirement then though going forward.

The `gsettings` solution covers me for now though - Thanks again for all the work @puxplaying !
