### ISSUE TITLE
Scale option disappeared 

### ISSUE THREAD

**Issue by kart972** [puxplaying/gnome-control-center-x11-scaling#4]
On manjaro kernal 5.15.32-1 Scale option disappears from Settings nemu after installing **gnome-control-center-x11-scaling**. And it doesn't come back after installing default gnome-control-center. Is there a fix for that?

**Comment by puxplaying** [comment]
Hi, please don't use this package on Gnome 42, as the patches from Ubuntu have not been ported.
You can still use mutter-x11-scaling and enable/disable it via _gsettings_.

To enable fractional scaling after installation run:

    gsettings set org.gnome.mutter experimental-features "['x11-randr-fractional-scaling']"

To disable fractional scaling run:

    gsettings reset org.gnome.mutter experimental-features

**Comment by kart972** [comment]
Hi,
Thank you for your reply! I've already tried this command it doesn't help to get old scaling back (100%-200%) and scaling option is completely missing and can't be even set by command


```diff     
gsettings reset org.gnome.mutter experimental-features
```


And this doesn't help either

```diff
gsettings set org.gnome.mutter experimental-features "['x11-randr-fractional-scaling']"
```

I've tried almost everything that come up then you search "gnome scaling disappeared" like reset gnome config etc. besides reinstall manjaro, but I think it kind of end solution. Likely I encountered this not on my main pc

Does it beyond repair? Do you have any other advices? I will highly appreciate that!

Thanks in advance!

**Comment by puxplaying** [comment]
This sounds strange, as there should be nothing to prevent you from enabling/disabling scaling via gsetting if you have `mutter-x11-scaling` installed and are on Xorg.

Please provide the output of:
 - `echo $XDG_SESSION_TYPE`  
 - `gnome-shell --version`
 - `pacman -Qoq mutter`
 - `pacman -Qoq gnome-control-center`

**Comment by kart972** [comment]
![IMG_20220505_011433_665](https://user-images.githubusercontent.com/89076448/166742810-bad4711a-3155-4309-8656-8f73a78bce45.jpg)

I'm using Wayland because for some reason Xorg doesn't boot on my laptop

`wayland`
`GNOME Shell 41.5`
`mutter-x11-scaling`
`gnome-control-center-x11-scaling`

**Comment by puxplaying** [comment]
I'm unable to reproduce the issue on Wayland with Gnome 41.5.

To enable fractional scaling on Wayland run:
`gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`
See also: https://wiki.archlinux.org/title/HiDPI#Wayland

As a side note, you don't need `mutter-x11-scaling` and  `gnome-control-center-x11-scaling`  if you are using Wayland only, as those packages are primary for Xorg scaling.

**Comment by kart972** [comment]
I know. I just tried to install it on y second machine before installing on a main one. And this command doesn't work for me. I think it some how broke after installing because it work fine before, can it be related to my hardware ? It's old HP laptop model 14-bs702TU It has Intel® HD Graphics 400 maybe some how tide to the issue. Do you need some more information?

`gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`

**Comment by kart972** [comment]
I also noticed that when you run gnome-control-center in terminal in debug menu you can see that in constantly returning
`display-cc-panel debug  setting adjustment -1.000 to -1:-0`

**Comment by puxplaying** [comment]
> I think it some how broke after installing because it work fine before

I would suggest to install `gnome-control-center` and `mutter` from the repo, create a new user account and check if it works there when you enable it with the gsettings command posted above. So we can exclude any user changes.

> can it be related to my hardware ?

I honestly doubt it, since you stated that it worked before.
In case the result is the same on a fresh user account, maybe check it also on Ubuntu, to be sure that it is hardware related.

**Comment by kart972** [comment]
I tested that, it doesn't work. I wonder could it be that default profile corrupted too. Or I don't know something unrelated. Any more advises? and also by the way really thank you for help.

**Comment by puxplaying** [comment]
Your issue seems to be at least unrelated to this package, since you still have the same problem with the official packages.
In case you don't have a backup of a previous working state, you could try a fresh install or a different distro. The worst case would indeed be a hardware failure, which you indicated by not having a working Xorg session. That is to my knowledge very unusual.
