### ISSUE TITLE
Manjaro Gnome 43.2 not working

### ISSUE THREAD

**Issue by pstachula-dev** [puxplaying/gnome-control-center-x11-scaling#6]
I don't see, any effect. Scaling doesn't work, moving the toggle doesn't do anything.

![image](https://user-images.githubusercontent.com/230560/211110784-1e9fc0e7-289a-40f8-9366-7fe1ae5c92ba.png)

**Comment by puxplaying** [comment]
Does disable/enable solve it?
You can also enable it via _gsettings_, just restart the control-center after that:
`gsettings set org.gnome.mutter experimental-features "['x11-randr-fractional-scaling']"`

Also please post the output of:
`LANG=C pacman -Qi mutter | grep Name`

**Comment by pstachula-dev** [comment]
1. toggling the button, restarting, etc. did not help
2. tried to enable this command from CLI with no effect
3. output: "mutter-x11-scaling"

Now I installed this package using Pacman with AUR and everything started working. Quite strange.
https://aur.archlinux.org/packages/mutter-x11-scaling

**Comment by puxplaying** [comment]
Well that's strange indeed, but I'm glad it works now. Technically there should be no difference between the AUR package I provide and the one Manjaro ships. I do co-maintain the PKGBUILD on Manjaro, so if the issue is reproducible please open a bug report over there.

https://gitlab.manjaro.org/packages/extra/mutter-x11-scaling

**Comment by JokerDevops** [comment]
I also encountered this error. An error occurred when I used 'makepkg - srci' to install:
```
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> accountsservice
  -> cups-pk-helper
  -> gnome-bluetooth-3.0
  -> gnome-desktop-4
  -> gnome-online-accounts
  -> gnome-settings-daemon
  -> gsettings-desktop-schemas
  -> gtk4
  -> libgtop
  -> libnma-gtk4
  -> sound-theme-freedesktop
  -> upower
  -> libpwquality
  -> gnome-color-manager
  -> smbclient
  -> libmm-glib
  -> libgnomekbd
  -> libibus
  -> libgudev
  -> bolt
  -> udisks2
  -> libadwaita
  -> gsound
  -> colord-gtk4
  -> gcr
  -> libmalcontent

```

**Comment by yochananmarqos** [comment]
> I used 'makepkg - srci' 

Hint: You have a typo and no flags were actually passed to `makepkg`.

**Comment by JokerDevops** [comment]
> > I used 'makepkg - srci'
> 
> Hint: You have a typo and no flags were actually passed to `makepkg`.

I use `makepkg -srci`

**Comment by JokerDevops** [comment]
My operating system is kali 6.0 . My operating system is kali 6.0, but I use `gnome-control-center/kali-rolling, now 1:43.0-2 amd64 [installed, automatic]`

**Comment by yochananmarqos** [comment]
> My operating system is kali 6.0

Sorry, are you lost? How are you using `makepkg` on Kali? That's a Debian based system. Please don't hijack the issue with something completely unrelated.
