### ISSUE TITLE
adding to the AUR

### ISSUE THREAD

**Issue by nrbeaton** [puxplaying/gnome-control-center-x11-scaling#7]
Any interest in adding this to the AUR like `mutter-x11-scaling`? So we could keep it up to date automatically?

**Comment by puxplaying** [comment]
Well it was in the AUR some time back, but I removed it because at that time Ubuntu decided to stay on a older g-c-c release, which meant that the patches were not re-based for one gnome release cycle (6 months). But maybe it's time to give it another shot. :-)

**Comment by puxplaying** [comment]
Well, so here we go: https://aur.archlinux.org/packages/gnome-control-center-x11-scaling

**Comment by nrbeaton** [comment]
Awesome, thanks -- I'll try it out tonight.

**Comment by nrbeaton** [comment]
It works! Brilliant!
